language: java

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - oraclejdk8
env:
  - MONGODB=4.0.0
  - MONGODB=3.6.0
  - MONGODB=3.4.0
  - MONGODB=3.2.0


before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

script: mvn test
