language: java
jdk:
- oraclejdk8

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

env:
  matrix:
    - MONGODB=3.4.17

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

install: mvn package
script: mvn test
